---
- name: clear nodes
  hosts: nodes_testing
  become: yes
  gather_facts: false

  tasks:
    - name: remove folders
      shell: rm -rf /home/testnet/* && rm -rf /home/mainnet/*

    - name: Clear images
      shell: docker kill $(docker ps -q) && docker rm $(docker ps -a -q) && docker rmi $(docker images -q)
