---
- name: Set options for explorer
  hosts: explorer
  become: yes
  gather_facts: false
  vars_prompt:
    - name: mongoPassword
      prompt: Enter mongo pass

  tasks:
    - name: Add mongo ppa key
      sudo: yes
      apt_key: >
        keyserver=hkp://keyserver.ubuntu.com:80
        id=7F0CEB10
        state=present
    - name: Add mongo sources list
      sudo: yes
      lineinfile: >
        line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
        dest=/etc/apt/sources.list.d/mongodb.list
        state=present
        create=yes
    - name: Install mongo
      sudo: yes
      apt: name=mongodb-org state=latest update_cache=yes
