---
- name: Set options for new node
  hosts: nodes_testing
  become: yes
  gather_facts: false
  vars_prompt:
    - name: repo_key
      prompt: Enter key for image repo

  tasks:
    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow

    - name: Deny all incoming traffic
      community.general.ufw:
        rule: deny
        direction: in

    - name: Allow all outgoing traffic
      community.general.ufw:
        rule: allow
        direction: out

    - name: Limit connections on ssh to prevent brutforce
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Allow port range 44574-44575
      community.general.ufw:
        rule: allow
        port: 44574:44575
        proto: tcp
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull docker image
      shell: export CR_PAT={{ repo_key }} && echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin && docker pull ghcr.io/vxxl-project/vxxl:fork

    - name: Creates directory for mainnet
      file:
        path: /home/mainnet
        state: directory

    - name: Creates directory for testnet
      file:
        path: /home/testnet
        state: directory

    - name: Add user
      ansible.builtin.user:
        name: vxxl
        uid: 1000

    - name: Set permissions mainnet
      shell: chown -R vxxl /home/mainnet

    - name: Set permissions testnet
      shell: chown -R vxxl /home/testnet

    - name: Clear images
      shell: docker kill $(docker ps -q) && docker rm $(docker ps -a -q) && docker rmi $(docker images -q)

    - name: Start docker mainnet
      shell: docker run -d -v /home/testnet:/home/vxxl/.vxxl -p 44574:44574 -p 44477:44477  --restart=always  ghcr.io/vxxl-project/vxxl:fork

    - name: Start docker testnet
      shell: docker run -d -v /home/testnet:/home/vxxl/.vxxl -p 44575:44575 -p 44478:44478  --restart=always  ghcr.io/vxxl-project/vxxl:fork -testnet
